openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
paths:
  "/auth/newToken":
    post:
      operationId: generateToken
      x-vertx-event-bus: com.oasis.social.service.ILoginService
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Something wrong happened
